version: "3.7"
services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Admin000*"
      MYSQL_DATABASE: "padrinos"
    volumes:
      - ./data/var/lib/mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
   
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "81:80"

  padrinos:
    image: padrinos:2
    restart: always
    ports:
      - "80:8000"
